### PR TITLE
feat: script to get user flags

### PR DESCRIPTION
**Pull request by rebelchris**
Introducing a script to get user flags for a specific user ID.

Usage:

```bash
yarn run babel-node src/scripts/getUserFlags.js "{user_id}"
```
Screenshot 2022-06-03 at 21 18 20

### CODE REVIEW

**Review by sshanzel — APPROVED** [review]
Nice! Thank you for this! 🙇

**Review by idoshamun — APPROVED** [review]
Important to mention that it goes directly to Flagsmith as opposed to the production setup that checks Redis first. But still a valuable script to have!

**Comment by rebelchris** [comment]
@idoshamun Oh thanks for that, this is how we address it in the boot query now, is that incorrect then?
I thought our implementation would globally take the caching option no matter how you call it?

**Comment by idoshamun** [comment]
@rebelchris you're right as long as you are connected to the same redis instance which is not possible from local machines. We will have to run it in the production instance which is doable of course. But it's important to keep this nuance in mind

**Pull request merged**
