### PR TITLE
fix: image upload to point to API

### PR DESCRIPTION
**Pull request by sshanzel**
As the API is the source of truth, we also need to redirect the image request to it.

### CODE REVIEW

**Review by rebelchris — APPROVED** [review]
That will do for now.

Is the one in the new auth version directly linked to API?
Just making sure we can eventually delete this call.

**Comment by sshanzel** [comment]
This is just the old one that still calls the gateway for changing images.

> Is the one in the new auth version directly linked to API?

Yes, the new one is directly calling the API.

**Review by idoshamun — APPROVED** [review]
Please validate in prod after the deployment

**Comment by sshanzel** [comment]
Works as intended now!

Preview:

image

**Comment by idoshamun** [comment]
You gotta love the image you used!

**Pull request merged**
