### PR TITLE
fix(router): redirect to "/" path

### PR DESCRIPTION
**Pull request by BudhirajaMadhav**
fix the redirect of `https://api.daily.dev` to `https://daily.dev`

### CODE REVIEW

**Review by idoshamun — APPROVED** [review]
Looks great! 😃
Thanks a lot for the contribution

**Comment by BudhirajaMadhav** [comment]
Just curious, why is the CI showing "Waiting for status to be reported"?

**Comment by idoshamun** [comment]
I disabled it for forks because someone abused it. But I might need to enable it so we can see if everything works here

**Comment by idoshamun** [comment]
I re-enabled the fork CI. But you need to push something so it can be re-triggered

**Comment by idoshamun** [comment]
@BudhirajaMadhav can you try and push something to trigger the CI please?

**Comment by idoshamun** [comment]
The failing test doesn't seem to have anything to do with this and the docker step doesn't meant to succeed for forks

**Comment by BudhirajaMadhav** [comment]
Really sorry @idoshamun, I was away for some days due to my ongoing exams. But happy to see this merged.

**Comment by idoshamun** [comment]
No worries. I hope you did well in the exams! :)

**Pull request merged**
